### ISSUE TITLE
Possibility to have constant "recording"?

### ISSUE THREAD

**Issue by fortiko** [HabitatMap/AirCasting#10]
In our scenario, we would like the non-technical user to carry the airbeam and the mobile phone around with them for 2-3 days in a row, constantly measuring and at the same time constantly uploading the data via 3G or LTE to our custom backend server.

This would enable "near real-time" monitoring for the school science project we have in mind.

Is there a way of re-programming the AirBeam mobile app so it transmits data continuously without the need for a user to start/stop sessions? Perhaps start/stop a session automatically every 10 or 30 minutes, or change from "sessions" to constant data transmissions?

Any suggestions on how to achieve that?

Thank you very much in advance.

**Comment by szemek** [comment]
@fortiko you can find Android application here: https://github.com/HabitatMap/AirCastingAndroidClient
