### ISSUE TITLE
WARNING: Can't mass-assign protected attributes

### ISSUE THREAD

**Issue by fortiko** [HabitatMap/AirCasting#11]
After recording a session and submitting for crowd map on my own instance, I get the following warning:

```
WARNING: Can't mass-assign protected attributes: uuid, end_time, location, streams, notes, start_time, os_version, phone_model, offset_60_db, deleted, contribute, calibration
```

on Ubuntu 14.04.3 LTS. At the same time, I cannot see any of the sessions in the web interface.

Are those things related? Thanks!

**Comment by tomaszgieres** [comment]
@fortiko I've done some work on Aircasting. I don't know everything that happens in background but they're probably not related. Aircasting seems to work correcly and fine at least on the official server. I'll try to schedule some time next days to see that.
If you have any more information on details that may be useful please provide them. Thanks.

**Comment by markusc** [comment]
@fortiko you need to run sidekiq to save sessions properly:

`bundle exec sidekiq -d`

**Comment by fortiko** [comment]
@marekciupak Thanks for that hint, it seemed to be missing from the documentation. This has been working for weeks now, sorry I forgot to save the ticket!
