### ISSUE TITLE
Parametre - sensor list are empty

### ISSUE THREAD

**Issue by ahmed-isi** [HabitatMap/AirCasting#113]
Hello

we have deployed your great application on our server, and we ordered an AirBeam sensor for test, but in the web site we find that both parametre - sensor list are empty, is this normal?

thank you to explain us how to feed them ..

Regards

**Comment by mheimbinder** [comment]
If you've set up your server correctly, then after you submit data from an
instrument, the "Parameter" and "Sensor" fields will populate.

-Michael-
--------------------
Michael Heimbinder
Executive Director, HabitatMap
347.410.9499
www.habitatmap.org
www.aircasting.org
www.takingspace.org
twitter.com/habitatmap
