### ISSUE TITLE
FixedSession measurement returning HTTP/500

### ISSUE THREAD

**Issue by lissyx** [HabitatMap/AirCasting#117]
I have own-built sensors pushing for years on AirCasting.org. Since feb 19th, at ~15:20 (Paris time), no more value are being pushed: server returns HTTP/500 error. This matches with merging #104.

Debugging further I could find that the 500 error code is triggered because of the time in the payload. More specifically, it seems that ISO8601 format which was accepted is triggering that:
```
"time": "2019-02-21T13:06:00.000+01:00"
```

No more error if I change the code to produce:
```
"time": "2019-02-21T13:06:00.000"
```

Looking at the history, I could not clearly identify a specific part of the changes that would explain this, so i'm wondering if it's on-purpose or a nasty side-effect / regression. Other valid ISO8601 like "2019-02-21T13:06:00Z" also gets rejected with HTTP/500.

The same values are okay when doing a POST request to create a new session. Only pushing measures to existing or new session triggers that error.

**Comment by lissyx** [comment]
Maybe @AkkarinForest or @3v0k4 could help me diagnosing if it's a regression or not?

**Comment by 3v0k4** [comment]
Hey @lissyx. I'm really sorry for the inconvenience.

I see that your requests are failing here https://github.com/HabitatMap/AirCasting/blob/master/app/models/stream.rb#L137. In particular, https://github.com/zdennis/activerecord-import tries to insert and fails:
```
ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect datetime value: '2019-02-22T10:42:38.000+01:00' for column 'time' at row 1: INSERT INTO `measurements` (`id`,`value`,`latitude`,`longitude`,`time`,`timezone_offset`,`stream_id`,`milliseconds`,`measured_value`) VALUES (NULL,58.0,47.34756,0.615198,'2019-02-21T13:06:00.000+01:00',60,114454,0,58.0)
```
The errors comes from the fact that ISO8601 is not a [valid datetime literal for MySql](https://dev.mysql.com/doc/refman/5.7/en/date-and-time-literals.html).

I'm not sure what have caused the change in behaviour. I believe [AirCasting's sensors](http://aircasting.org/about) are all using a format that MySql supports. Also, timezones are not taken into account by the app at the moment: all times are assumed as local times. In that sense, the timezone is redundant.

Would it be possible for you to change your setup to send times as described in MySql docs from above?

**Comment by lissyx** [comment]
> Would it be possible for you to change your setup to send times as described in MySql docs from above?

Sure, but it's a bit inconvenient, and I'm wondering if it should be considered a regression. I understand that it's not the format supported by MySQL, but I don't think you changed the database with the upgrade, so I suspect some magic conversion was done by RoR in the past. For someone not used to the architecture, it's not clear what is the format.

Yet, I understand there's no really officially supported API, so either decision is going to be fine by me, I just thought this was a regression and thus wanted to make sure (I got other breakages after the upgrade, but those were on session creation, one being a typo on the `description field`, the other one being the `location` field that seemed to have disappeared).

So if you think it's not a regression, let's close that and I'll update my fix to produce MySQL-compatible and not ISO8601 (but I'm pretty sure this format was suggested / documented by the project or someone from the project when I started working).

**Comment by 3v0k4** [comment]
I really appreciate you taking the time to open the issue. We are trying to remove some cruft from the codebase and in the process I'm sure we made and will make some mistakes. It's incredibly valuable to have feedback like yours. And I'm sorry if this causes problems to users.

The easiest thing for now would be to change your setup. I'm leaving it to @mheimbinder to elaborate more on this issue.

**Comment by lissyx** [comment]
> We are trying to remove some cruft from the codebase and in the process I'm sure we made and will make some mistakes. It's incredibly valuable to have feedback like yours. And I'm sorry if this causes problems to users.

That's okay. Updating devices will be possible (and required, since session creation broke is some legit way) but some of the are now far awar from me, so I'll try to do my best.
