### ISSUE TITLE
I cannot find settings on AirCasting app

### ISSUE THREAD

**Issue by annettelang** [HabitatMap/AirCasting#13]
where do I find the settings tab

**Comment by mheimbinder** [comment]
It sounds as if you are using the AirCasting app and are looking to access the "Settings" via the menu button.  On most Samsung phones, the menu button is hidden.  To access it, launch the AirCasting app, then press and hold one of the hard buttons along the bottom of the screen.  It's usually but not always the "recent" button.  Failing that, try Googling your phone's make and model plus the phrase "menu button".

-Michael-

**Comment by annettelang** [comment]
Thank you!
