### ISSUE TITLE
The sessions API call doesn't seem to be working?

### ISSUE THREAD

**Issue by mking007** [HabitatMap/AirCasting#16]
The example in the API documentation doesn't seem to work:
http://aircasting.org/api/sessions/9586

Nor does any other variation I've tried

**Comment by mheimbinder** [comment]
You have to append the desired format to the end of the url, e.g. http://aircasting.org/api/sessions/9586.json.  We updated the documentation accordingly.

**Comment by mking007** [comment]
Thanks 👍
