### ISSUE TITLE
Sessions API returns inconsistent results

### ISSUE THREAD

**Issue by danwahl** [HabitatMap/AirCasting#242]
The [provided example](https://github.com/HabitatMap/AirCasting/blob/master/doc/api.md) returns 23 results:

[http://aircasting.org/api/sessions.json?page=0&page_size=50&q[measurements]=true&q[time_from]=0&q[time_to]=1552648500&q[usernames]=HHHDenver&q[location]=Denver&q[sensor_name]=AirBeam-PM&q[unit_symbol]=µg/m³](http://aircasting.org/api/sessions.json?page=0&page_size=50&q[measurements]=true&q[time_from]=0&q[time_to]=1552648500&q[usernames]=HHHDenver&q[location]=Denver&q[sensor_name]=AirBeam-PM&q[unit_symbol]=µg/m³)

However, changing `q[time_to]` the current (as of this post) epoch time returns only four:

[http://aircasting.org/api/sessions.json?page=0&page_size=50&q[measurements]=true&q[time_from]=0&q[time_to]=1559363588&q[usernames]=HHHDenver&q[location]=Denver&q[sensor_name]=AirBeam-PM&q[unit_symbol]=%C2%B5g/m%C2%B3](http://aircasting.org/api/sessions.json?page=0&page_size=50&q[measurements]=true&q[time_from]=0&q[time_to]=1559363588&q[usernames]=HHHDenver&q[location]=Denver&q[sensor_name]=AirBeam-PM&q[unit_symbol]=%C2%B5g/m%C2%B3)

It also appears that `q[time_from]` and `q[time_to]` are now required fields, as queries without either return a 500 error:

[http://aircasting.org/api/sessions.json?page=0&page_size=50&q[measurements]=true&q[usernames]=HHHDenver&q[location]=Denver&q[sensor_name]=AirBeam-PM&q[unit_symbol]=%C2%B5g/m%C2%B3](http://aircasting.org/api/sessions.json?page=0&page_size=50&q[measurements]=true&q[usernames]=HHHDenver&q[location]=Denver&q[sensor_name]=AirBeam-PM&q[unit_symbol]=%C2%B5g/m%C2%B3)

**Comment by mheimbinder** [comment]
The time filter actually consists of two separate filters: date and hour. The timestamp you are using in the link is for June 1, 2019 4:33:08 AM, so only the sessions recorded between midnight and 4:33 AM are returned.  If you wish to see all sessions from the beginning of time through June 1 use 1559433599, which translates to June 1, 2019 11:59:59 PM.  

Thanks for bringing this issue to our attention.  We'll update the documentation to make this clearer for future API users.

-Michael-
