### ISSUE TITLE
Can I delete a point from a session that appear to be erroneous? 

### ISSUE THREAD

**Issue by amyp530** [HabitatMap/AirCasting#27]
One session appears to have a point with incorrect GPS points. Would it be possible to delete this point from the AirCasting server?

**Comment by mheimbinder** [comment]
Unfortunately this is not possible.

-Michael-

--------------------
Michael Heimbinder
Executive Director, HabitatMap
347.410.9499
www.habitatmap.org
www.aircasting.org
www.takingspace.org
twitter.com/habitatmap
