### ISSUE TITLE
Example request returns an Internal server error.

### ISSUE THREAD

**Issue by georgeslabreche** [HabitatMap/AirCasting#299]
The documentation provides this sample request:

```
curl http://aircasting.org/api/mobile/sessions.json?limit=50&offset=0&q[measurements]=true&q[time_from]=0&q[time_to]=1552648500&q[usernames]=HHHDenver&q[location]=Denver&q[sensor_name]=AirBeam-PM&q[unit_symbol]=µg/m³
```

Which returns an Internal Server Error:
```
{
    "status":500,
    "error":"Internal Server Error"
}
```

Every request I try is returning an internal server error. The error message is not verbose enough to figure out if this is a malformed request issue or a server issue.

**Comment by mheimbinder** [comment]
Hi Georges.  Thanks for getting in touch.  We recently made some updates to
the API endpoints and are in the process of updating the API documentation
on GitHub.  I expect this to be done by COB tomorrow.  I'll circle back
around with you once this work has been completed.  My apologies for the
inconvenience.

-Michael-
--------------------
Michael Heimbinder
Executive Director, HabitatMap
347.410.9499
www.habitatmap.org
www.aircasting.org
www.takingspace.org
twitter.com/habitatmap

**Comment by mheimbinder** [comment]
Hi Georges.  We updated the API documentation just now.  Please have a look
and let me know if you have any questions.

-Michael-

--------------------
Michael Heimbinder
Executive Director, HabitatMap
347.410.9499
www.habitatmap.org
www.aircasting.org
www.takingspace.org
twitter.com/habitatmap

**Comment by georgeslabreche** [comment]
Thank you for being so responsive with this issue.

 **GET /api/region**
The example given for this request returns null data:

`{ "average":null,
    "number_of_contributors":0,
    "number_of_samples":0}`

**GET /api/measurements.json** 
The example given for this request does not work for me unless I use single quote marks. This is however not an issue with other example requests that do not use single quote marks. Not sure what's the deal.

**GET /api/averages**
The example works but takes a long time to process. You might want to consider a less demanding request.

**Comment by mheimbinder** [comment]
Hi Georges.  Thanks again for your feedback.  We're in the process of
responding and will be back in touch soon to let you know the errors and
oversights you identified have been corrected.

-Michael-

--------------------
Michael Heimbinder
Executive Director, HabitatMap
347.410.9499
www.habitatmap.org
www.aircasting.org
www.takingspace.org
twitter.com/habitatmap

**Comment by mheimbinder** [comment]
Hi Georges.  We added better examples for GET /api/region and GET /api/averages.  Please do follow up if you run into any other issues or have additional feedback.

-Michael-
