### ISSUE TITLE
Calculations grid on crowd map

### ISSUE THREAD

**Issue by FrozoneAirPol** [HabitatMap/AirCasting#30]
Hey, 

I'm kind of new in data processing and I try to use aircasting data. I downloaded all the session I was interested in and processing the data in R. 
I was wondering how the colors where defined on the map to use the same method but for different shapes. I tried to search here on github where the calculations where made, but didn't find the code. Does anyone knows where to find these calculations? 

Thanks

**Comment by mheimbinder** [comment]
The thresholds between colors are defined on the "Heat Legend"

-Michael-

--------------------
Michael Heimbinder
Executive Director, HabitatMap
347.410.9499
www.habitatmap.org
www.aircasting.org
www.takingspace.org
twitter.com/habitatmap

**Comment by FrozoneAirPol** [comment]
So you mean that if the threshold 55µg/m³ is the threshold of the heat legend for red. If this threshold was passed just once in the square in the given time range, the whole square will  red?

**Comment by mheimbinder** [comment]
All the measurements within the polygon are averaged together.  The average
is what is taken into account when determining the color.

-Michael-

--------------------
Michael Heimbinder
Executive Director, HabitatMap
347.410.9499
www.habitatmap.org
www.aircasting.org
www.takingspace.org
twitter.com/habitatmap

**Comment by FrozoneAirPol** [comment]
Ok, thanks. 
Just one last question then. How do you handle the averages? Do you average each session and then average the different sessions averages or do you average all the measurements?

**Comment by mheimbinder** [comment]
We average all the measurements in the area defined by the polygon.

-Michael-

--------------------
Michael Heimbinder
Executive Director, HabitatMap
347.410.9499
www.habitatmap.org
www.aircasting.org
www.takingspace.org
twitter.com/habitatmap

**Comment by FrozoneAirPol** [comment]
Ok, perfect. Thanks 👍
