### ISSUE TITLE
Incorrect timezone

### ISSUE THREAD

**Issue by coenvl** [HabitatMap/AirCasting#302]
When I retrieve measurements from the web API, the time is incorrect.

I am using an AirBeam sensor to stream data to the backend, and retrieve the data through the API. However, the timing of the measurements is incorrect. I believe the issue is also related to the firmware on the AirBeam sensor; it seems to send the data to the backend without any timezone indication. However when I retrieve it from the API, a 'Z' is appended, which is not correct. I am in UTC+2, so the measurements seem to come from the future.

Is this a misconfiguration of the client? I.e. can I change the timezone of the sensor to use UTC, or is this indeed a bug that needs to be fixed?

This is where the timezone is omitted:
https://github.com/HabitatMap/AirCastingAndroidClient/blob/f80c4065f6b721353042f7857f4a31c8f2ad3599/arduino/aircasting/Airbeam2_Firmware_3_19_18/Build_String.cpp#L416

**Comment by mheimbinder** [comment]
Hi Ceon.   Thanks for getting in touch.  A couple questions and a request:

1) Are you sending data via WiFi or cellular.
2) If via WiFi, is the time on the phone you used to configure the AirBeam
correct?
3) Please email the data you downloaded to info@habitatmap.org

Thanks.

-Michael-

--------------------
Michael Heimbinder
Executive Director, HabitatMap
347.410.9499
www.habitatmap.org
www.aircasting.org
www.takingspace.org
twitter.com/habitatmap

**Comment by coenvl** [comment]
Hi, thanks for the quick response.

1. I am using WiFi
2. The time on my phone which I configured the AirBeam with is correct according to the local time zone.
3. I could if you want, but perhaps a link to the api response is easier: http://aircasting.org/api/measurements.json?stream_ids=310249&start_time=1557736796000&end_time=1557823196000

Thanks already

**Comment by mheimbinder** [comment]
Hi Coen.  When pulling data via the API, all times will be in UTC.  If you
need time zones, export the sessions via the app or website.

-Michael-

--------------------
Michael Heimbinder
Executive Director, HabitatMap
347.410.9499
www.habitatmap.org
www.aircasting.org
www.takingspace.org
twitter.com/habitatmap

**Comment by coenvl** [comment]
Yes, the time is **suppposedly** in UTC, but it is incorrect. The airbeam uploads a measurements with a timestamp, say "*2019-05-13T08:41:34*", at 8:41 local time. If I get that same measurement back from the API it says "*2019-05-13T08:41:34Z*" (note the last Z). This means that the measurement now seems to come from the future.

**Comment by mheimbinder** [comment]
Hi Coen.  Can you please do the following:

1) Turn off your AirBeam.
2) Turn on your AirBeam and listen to it over serial, be sure to catch the
serial output from the beginning.
3) After 4 minutes, copy and send the serial output to me at
info@habitatmap.org.

Thanks.

-Michael-

--------------------
Michael Heimbinder
Executive Director, HabitatMap
347.410.9499
www.habitatmap.org
www.aircasting.org
www.takingspace.org
twitter.com/habitatmap
