### ISSUE TITLE
Get sensorId from APi

### ISSUE THREAD

**Issue by coenvl** [HabitatMap/AirCasting#333]
I have multiple airbeam sensors, and I would like to have some way to programmatically determine which sensor provided a measurement. A non-programmatic method would be to add a tag, or use the session title, from which I can manually determine the sensor. However this is prone to error, so I am wondering if the API supports something like this? 

The sensor_package_name looks like this is something that I could need, but this changes from one session to another. Ideally a session (or a stream) would contain some sensorId field, with a unique identifier, which does not change between sessions.

**Comment by mheimbinder** [comment]
Hi Coen.  You can use the sensor package name as it is a unique identifier
that incorporates the AirBeams unique MAC address and never changes.

-Michael-

--------------------
Michael Heimbinder
Executive Director, HabitatMap
347.410.9499
www.habitatmap.org
www.aircasting.org
www.takingspace.org
twitter.com/habitatmap

**Comment by coenvl** [comment]
Is it really, that must have been my misunderstanding then. Thank you for the quick reply, and I will close this issue.
